namespace Nevermind.ByteCode.Instructions.ArithmeticInstructions
{
    internal enum BinaryArithmeticInstructionType
    {
        A_Add,
        A_Sub,
        A_Mul,
        A_Div,
        A_lseq,
        A_ls,
        A_gr,
        A_greq,
        A_neq,
        A_eq,
        A_EDiv,
        A_LAnd,
        A_LOr,
        A_And,
        A_Xor,
        A_Or,
        A_lsh,
        A_rlh,
        A_SetAdd,
        A_SetSub,
        A_SetMul,
        A_SetDiv,
        A_SetEDiv,
        A_SetAnd,
        A_SetXor,
        A_SetOr,
        A_Set,
    }
}
